name: fetch duckdb static libs
on:
  workflow_dispatch:
jobs:
  update-darwin-amd64-bindings:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-osx-amd64.zip
          rm -rf darwin_amd64/libs
          mkdir darwin_amd64/libs
          rm -f darwin_amd64/duckdb.h
          unzip static-lib-osx-amd64.zip
          mv libduckdb_bundle.a darwin_amd64/libs/libduckdb.a
          mv duckdb.h darwin_amd64/duckdb.h
          rm -f static-lib-osx-amd64.zip
        shell: bash
  #      - name: commit
  #        uses: stefanzweifel/git-auto-commit-action@v5
  #        with:
  #          commit_message: push v1.2.0 darwin amd64 static lib
  update-darwin-arm64-bindings:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-osx-arm64.zip
          rm -rf darwin_arm64/libs
          mkdir darwin_arm64/libs
          rm -f darwin_arm64/duckdb.h
          unzip static-lib-osx-arm64.zip
          mv libduckdb_bundle.a darwin_arm64/libs/libduckdb.a
          mv duckdb.h darwin_arm64/duckdb.h
          rm -f static-lib-osx-arm64.zip
        shell: bash
#      - name: commit
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: push v1.2.0 darwin arm64 static lib
  update-linux-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static libs
        run: |
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-linux-amd64.zip
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-linux-arm64.zip
          rm -rf linux_amd64/libs
          mkdir linux_amd64/libs
          rm -f linux_amd64/duckdb.h
          unzip static-lib-linux-amd64.zip
          mv libduckdb_bundle.a linux_amd64/libs/libduckdb.a
          mv duckdb.h linux_amd64/duckdb.h
          rm -f static-lib-linux-amd64.zip
          rm -rf linux_arm64/libs
          mkdir linux_arm64/libs
          rm -f linux_arm64/duckdb.h
          unzip static-lib-linux-arm64.zip
          mv libduckdb_bundle.a linux_arm64/libs/libduckdb.a
          mv duckdb.h linux_arm64/duckdb.h
          rm -f static-lib-linux-arm64.zip
        shell: bash
  #      - name: commit
  #        uses: stefanzweifel/git-auto-commit-action@v5
  #        with:
  #          commit_message: push v1.2.0 darwin amd64 static lib
  update-windows-amd64-asd:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-windows-mingw.zip
          rm -rf windows_amd64/libs
          mkdir windows_amd64/libs
          rm -f windows_amd64/duckdb.h
          unzip static-lib-windows-mingw.zip
          mv libduckdb_bundle.a windows_amd64/libs/libduckdb.a
          mv duckdb.h windows_amd64/duckdb.h
          rm -f static-lib-windows-mingw.zip
        shell: bash
#      - name: Push updated bindings
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: Push updated bindings
