name: Fetch Windows
on:
  workflow_dispatch:
jobs:
  fetch-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch Windows
        run: |
          make fetch.static.lib.mingw DIRECTORY=windows_amd64
          make split.artefacts DIRECTORY=windows_amd64 FILETYPE=obj
        shell: bash
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push windows libs
