name: fetch duckdb static libs
on:
  workflow_dispatch:
jobs:
  update-darwin-amd64-bindings:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          cd darwin_amd64
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-osx-amd64.zip
          rm -rf libs
          mkdir libs
          rm -f duckdb.h
          unzip static-lib-osx-amd64.zip
          mv libduckdb_bundle.a libs/libduckdb.a
          rm -f static-lib-osx-amd64.zip
        shell: bash
  #      - name: commit
  #        uses: stefanzweifel/git-auto-commit-action@v5
  #        with:
  #          commit_message: push v1.2.0 darwin amd64 static lib
  update-darwin-arm64-bindings:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          cd darwin_arm64
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-osx-arm64.zip
          rm -rf libs
          mkdir libs
          rm -f duckdb.h
          unzip static-lib-osx-arm64.zip
          mv libduckdb_bundle.a libs/libduckdb.a
          rm -f static-lib-osx-arm64.zip
        shell: bash
#      - name: commit
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: push v1.2.0 darwin arm64 static lib
  update-linux-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static libs
        run: |
          cd linux_amd64
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-linux-amd64.zip
          rm -rf libs
          mkdir libs
          rm -f duckdb.h
          unzip static-lib-linux-amd64.zip
          mv libduckdb_bundle.a libs/libduckdb.a
          rm -f static-lib-linux-amd64.zip
          cd ..
          make split.linux.amd64.artefacts
          cd linux_arm64
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-linux-arm64.zip
          rm -rf libs
          mkdir libs
          rm -f duckdb.h
          unzip static-lib-linux-arm64.zip
          mv libduckdb_bundle.a libs/libduckdb.a
          rm -f static-lib-linux-arm64.zip
        shell: bash
  #      - name: commit
  #        uses: stefanzweifel/git-auto-commit-action@v5
  #        with:
  #          commit_message: push v1.2.0 darwin amd64 static lib
  update-windows-amd64-asd:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: curl static lib
        run: |
          cd windows_amd64
          curl -OL https://github.com/duckdb/duckdb/releases/download/v1.2.0/static-lib-windows-mingw.zip
          rm -rf libs
          mkdir libs
          rm -f duckdb.h
          unzip static-lib-windows-mingw.zip
          mv libduckdb_bundle.a libs/libduckdb.a
          rm -f static-lib-windows-mingw.zip
        shell: bash
#      - name: Push updated bindings
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: Push updated bindings
