name: fetch static libs
on:
  workflow_dispatch:
jobs:
  fetch-darwin-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: fetch darwin static libs
        run: |
          make fetch.static.lib DIRECTORY=darwin_arm64 VERSION=v1.2.0 FILENAME=static-lib-osx-amd64
          make fetch.static.lib DIRECTORY=darwin_amd64 VERSION=v1.2.0 FILENAME=static-lib-osx-arm64
      - name: fetch and split linux static libs
        run: |
          make fetch.static.lib DIRECTORY=linux_amd64 VERSION=v1.2.0 FILENAME=static-lib-linux-amd64
          make split.artefacts DIRECTORY=linux_amd64
          make fetch.static.lib DIRECTORY=linux_arm64 VERSION=v1.2.0 FILENAME=static-lib-linux-arm64
          make split.artefacts DIRECTORY=linux_arm64
        shell: bash
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push v1.2.0 darwin and linux
  fetch-windows:
    runs-on: windows-2019
    needs: [fetch-darwin-linux]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: fetch and split windows static lib
        run: |
          make fetch.static.lib DIRECTORY=windows_amd64 VERSION=v1.2.0 FILENAME=static-lib-windows-mingw
          make split.artefacts DIRECTORY=windows_amd64
        shell: bash
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push v1.2.0 windows
