name: fetch static libs for windows
on:
  workflow_dispatch:
jobs:
  fetch-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: fetch and split windows static lib
        run: |
          make fetch.static.lib DIRECTORY=windows_amd64 VERSION=v1.2.0 FILENAME=static-lib-windows-mingw
          make split.artefacts DIRECTORY=windows_amd64 FILETYPE=o
        shell: bash
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push v1.2.0 windows
