name: Tests
on:
  workflow_dispatch:

jobs:
  go-tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: "macos-13"
            dir: "darwin-amd64"
          - os: "macos-14"
            dir: "darwin-arm64"
          - os: "ubuntu-latest"
            dir: "linux-amd64"
          - os: "ubuntu-24.04-arm"
            dir: "linux-arm64"
          - os: "windows-latest"
            dir: "windows-amd64"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test ${{ matrix.dir }} ${{ matrix.dir }}
        run: |
          cd ${{ matrix.dir }}
          go test
