name: Update the duckdb version
on:
  workflow_dispatch:
jobs:
  update-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
