name: Update Module Bindings
on:
  workflow_dispatch:
jobs:
  update-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Replace Bindings
        shell: bash
        run: |
          make update.binding DIRECTORY=darwin-amd64
          make update.binding DIRECTORY=darwin-arm64
          make update.binding DIRECTORY=linux-amd64
          make update.binding DIRECTORY=linux-arm64
          make update.binding DIRECTORY=windows-amd64
      - name: Push Updated Bindings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push updated bindings
